/* Generated by Yosys 0.55+158 (git sha1 da01e1768, g++ 15.1.1 -fPIC -O3) */

(* src = "baud_rate_selector.v:1.1-54.10" *)
module baud_sel_gen(baud_sel, clk, rst, enable_baud, baud);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  (* src = "baud_rate_selector.v:3.12-3.23" *)
  wire [23:0] accumulator;
  (* src = "baud_rate_selector.v:1.87-1.91" *)
  output baud;
  wire baud;
  (* src = "baud_rate_selector.v:1.33-1.41" *)
  input [1:0] baud_sel;
  wire [1:0] baud_sel;
  (* src = "baud_rate_selector.v:1.48-1.51" *)
  input clk;
  wire clk;
  (* src = "baud_rate_selector.v:1.68-1.79" *)
  input enable_baud;
  wire enable_baud;
  (* src = "baud_rate_selector.v:1.58-1.61" *)
  input rst;
  wire rst;
  sky130_fd_sc_hd__and2_0 _137_ (
    .A(baud_sel[0]),
    .B(baud_sel[1]),
    .X(_091_)
  );
  sky130_fd_sc_hd__xor2_1 _138_ (
    .A(accumulator[14]),
    .B(_091_),
    .X(_092_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _139_ (
    .A(baud_sel[1]),
    .SLEEP(baud_sel[0]),
    .X(_093_)
  );
  sky130_fd_sc_hd__nand2b_1 _140_ (
    .A_N(baud_sel[0]),
    .B(baud_sel[1]),
    .Y(_094_)
  );
  sky130_fd_sc_hd__nor2_1 _141_ (
    .A(accumulator[13]),
    .B(_093_),
    .Y(_095_)
  );
  sky130_fd_sc_hd__nand2_1 _142_ (
    .A(accumulator[13]),
    .B(_093_),
    .Y(_096_)
  );
  sky130_fd_sc_hd__nor2b_1 _143_ (
    .A(_095_),
    .B_N(_096_),
    .Y(_097_)
  );
  sky130_fd_sc_hd__nand2b_1 _144_ (
    .A_N(baud_sel[1]),
    .B(baud_sel[0]),
    .Y(_098_)
  );
  sky130_fd_sc_hd__nand2_1 _145_ (
    .A(_094_),
    .B(_098_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__nand2_1 _146_ (
    .A(accumulator[12]),
    .B(_099_),
    .Y(_100_)
  );
  sky130_fd_sc_hd__xnor2_1 _147_ (
    .A(accumulator[12]),
    .B(_099_),
    .Y(_101_)
  );
  sky130_fd_sc_hd__nand2_1 _148_ (
    .A(accumulator[11]),
    .B(_094_),
    .Y(_102_)
  );
  sky130_fd_sc_hd__nor2_1 _149_ (
    .A(accumulator[11]),
    .B(_094_),
    .Y(_103_)
  );
  sky130_fd_sc_hd__nor2_1 _150_ (
    .A(baud_sel[0]),
    .B(baud_sel[1]),
    .Y(_104_)
  );
  sky130_fd_sc_hd__and2_0 _151_ (
    .A(accumulator[10]),
    .B(_104_),
    .X(_105_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _152_ (
    .A(accumulator[10]),
    .SLEEP(_104_),
    .X(_106_)
  );
  sky130_fd_sc_hd__nand2b_1 _153_ (
    .A_N(_105_),
    .B(_106_),
    .Y(_107_)
  );
  sky130_fd_sc_hd__nand2_1 _154_ (
    .A(accumulator[9]),
    .B(baud_sel[1]),
    .Y(_108_)
  );
  sky130_fd_sc_hd__nor2_1 _155_ (
    .A(accumulator[9]),
    .B(baud_sel[1]),
    .Y(_109_)
  );
  sky130_fd_sc_hd__clkinv_1 _156_ (
    .A(_109_),
    .Y(_110_)
  );
  sky130_fd_sc_hd__and2_0 _157_ (
    .A(accumulator[8]),
    .B(baud_sel[0]),
    .X(_111_)
  );
  sky130_fd_sc_hd__xnor2_1 _158_ (
    .A(accumulator[7]),
    .B(_104_),
    .Y(_112_)
  );
  sky130_fd_sc_hd__and2_0 _159_ (
    .A(accumulator[6]),
    .B(baud_sel[1]),
    .X(_113_)
  );
  sky130_fd_sc_hd__xnor2_1 _160_ (
    .A(accumulator[6]),
    .B(baud_sel[1]),
    .Y(_114_)
  );
  sky130_fd_sc_hd__and2_0 _161_ (
    .A(accumulator[5]),
    .B(baud_sel[0]),
    .X(_115_)
  );
  sky130_fd_sc_hd__nor2_1 _162_ (
    .A(accumulator[5]),
    .B(baud_sel[0]),
    .Y(_116_)
  );
  sky130_fd_sc_hd__and2_0 _163_ (
    .A(accumulator[4]),
    .B(_098_),
    .X(_117_)
  );
  sky130_fd_sc_hd__nor2_1 _164_ (
    .A(accumulator[4]),
    .B(_098_),
    .Y(_118_)
  );
  sky130_fd_sc_hd__nor2_1 _165_ (
    .A(_117_),
    .B(_118_),
    .Y(_119_)
  );
  sky130_fd_sc_hd__nand2_1 _166_ (
    .A(accumulator[3]),
    .B(baud_sel[0]),
    .Y(_120_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _167_ (
    .A(accumulator[3]),
    .SLEEP(baud_sel[0]),
    .X(_121_)
  );
  sky130_fd_sc_hd__nand2_1 _168_ (
    .A(accumulator[2]),
    .B(_098_),
    .Y(_122_)
  );
  sky130_fd_sc_hd__and2_0 _169_ (
    .A(accumulator[1]),
    .B(baud_sel[0]),
    .X(_123_)
  );
  sky130_fd_sc_hd__nand2_1 _170_ (
    .A(accumulator[0]),
    .B(_098_),
    .Y(_124_)
  );
  sky130_fd_sc_hd__xor2_1 _171_ (
    .A(accumulator[1]),
    .B(baud_sel[0]),
    .X(_125_)
  );
  sky130_fd_sc_hd__a31oi_1 _172_ (
    .A1(accumulator[0]),
    .A2(_098_),
    .A3(_125_),
    .B1(_123_),
    .Y(_126_)
  );
  sky130_fd_sc_hd__xnor2_1 _173_ (
    .A(accumulator[2]),
    .B(_098_),
    .Y(_127_)
  );
  sky130_fd_sc_hd__o21ai_0 _174_ (
    .A1(_126_),
    .A2(_127_),
    .B1(_122_),
    .Y(_128_)
  );
  sky130_fd_sc_hd__o211ai_1 _175_ (
    .A1(_126_),
    .A2(_127_),
    .B1(_120_),
    .C1(_122_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__and2_0 _176_ (
    .A(_121_),
    .B(_129_),
    .X(_130_)
  );
  sky130_fd_sc_hd__a21oi_1 _177_ (
    .A1(_119_),
    .A2(_130_),
    .B1(_117_),
    .Y(_131_)
  );
  sky130_fd_sc_hd__a311oi_1 _178_ (
    .A1(_119_),
    .A2(_121_),
    .A3(_129_),
    .B1(_117_),
    .C1(_115_),
    .Y(_132_)
  );
  sky130_fd_sc_hd__nor3_1 _179_ (
    .A(_114_),
    .B(_116_),
    .C(_132_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__o21ai_0 _180_ (
    .A1(_104_),
    .A2(_113_),
    .B1(accumulator[7]),
    .Y(_134_)
  );
  sky130_fd_sc_hd__o41ai_1 _181_ (
    .A1(_112_),
    .A2(_114_),
    .A3(_116_),
    .A4(_132_),
    .B1(_134_),
    .Y(_135_)
  );
  sky130_fd_sc_hd__nor2_1 _182_ (
    .A(accumulator[8]),
    .B(baud_sel[0]),
    .Y(_136_)
  );
  sky130_fd_sc_hd__nor2_1 _183_ (
    .A(_111_),
    .B(_136_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__a21oi_1 _184_ (
    .A1(_135_),
    .A2(_025_),
    .B1(_111_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__a221o_1 _185_ (
    .A1(accumulator[9]),
    .A2(baud_sel[1]),
    .B1(_135_),
    .B2(_025_),
    .C1(_111_),
    .X(_027_)
  );
  sky130_fd_sc_hd__a21oi_1 _186_ (
    .A1(_108_),
    .A2(_026_),
    .B1(_109_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__a31oi_1 _187_ (
    .A1(_106_),
    .A2(_110_),
    .A3(_027_),
    .B1(_105_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__a21oi_1 _188_ (
    .A1(_102_),
    .A2(_029_),
    .B1(_103_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__a211oi_1 _189_ (
    .A1(_102_),
    .A2(_029_),
    .B1(_103_),
    .C1(_101_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__a21oi_1 _190_ (
    .A1(_096_),
    .A2(_100_),
    .B1(_095_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__maj3_1 _191_ (
    .A(accumulator[14]),
    .B(_091_),
    .C(_032_),
    .X(_033_)
  );
  sky130_fd_sc_hd__a21oi_1 _192_ (
    .A1(_097_),
    .A2(_031_),
    .B1(_032_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__a31oi_1 _193_ (
    .A1(_092_),
    .A2(_097_),
    .A3(_031_),
    .B1(_033_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__clkinv_1 _194_ (
    .A(_035_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__nand2_1 _195_ (
    .A(enable_baud),
    .B(accumulator[15]),
    .Y(_037_)
  );
  sky130_fd_sc_hd__nor2_1 _196_ (
    .A(_035_),
    .B(_037_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__nor3b_1 _197_ (
    .A(_035_),
    .B(_037_),
    .C_N(accumulator[16]),
    .Y(_039_)
  );
  sky130_fd_sc_hd__and3_1 _198_ (
    .A(accumulator[19]),
    .B(accumulator[18]),
    .C(accumulator[17]),
    .X(_040_)
  );
  sky130_fd_sc_hd__and3_1 _199_ (
    .A(accumulator[20]),
    .B(_039_),
    .C(_040_),
    .X(_041_)
  );
  sky130_fd_sc_hd__and3_1 _200_ (
    .A(accumulator[22]),
    .B(accumulator[21]),
    .C(_041_),
    .X(_042_)
  );
  sky130_fd_sc_hd__and4_1 _201_ (
    .A(accumulator[23]),
    .B(accumulator[22]),
    .C(accumulator[21]),
    .D(_041_),
    .X(_043_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _202_ (
    .A(_043_),
    .SLEEP(rst),
    .X(_000_)
  );
  sky130_fd_sc_hd__and3_1 _203_ (
    .A(enable_baud),
    .B(accumulator[0]),
    .C(_098_),
    .X(_044_)
  );
  sky130_fd_sc_hd__a21oi_1 _204_ (
    .A1(enable_baud),
    .A2(_098_),
    .B1(accumulator[0]),
    .Y(_045_)
  );
  sky130_fd_sc_hd__nor3_1 _205_ (
    .A(rst),
    .B(_044_),
    .C(_045_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__xor2_1 _206_ (
    .A(_124_),
    .B(_125_),
    .X(_046_)
  );
  sky130_fd_sc_hd__nor2_1 _207_ (
    .A(enable_baud),
    .B(accumulator[1]),
    .Y(_047_)
  );
  sky130_fd_sc_hd__a211oi_1 _208_ (
    .A1(enable_baud),
    .A2(_046_),
    .B1(_047_),
    .C1(rst),
    .Y(_002_)
  );
  sky130_fd_sc_hd__xnor2_1 _209_ (
    .A(_126_),
    .B(_127_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__nor2_1 _210_ (
    .A(enable_baud),
    .B(accumulator[2]),
    .Y(_049_)
  );
  sky130_fd_sc_hd__a211oi_1 _211_ (
    .A1(enable_baud),
    .A2(_048_),
    .B1(_049_),
    .C1(rst),
    .Y(_003_)
  );
  sky130_fd_sc_hd__and2_0 _212_ (
    .A(_120_),
    .B(_121_),
    .X(_050_)
  );
  sky130_fd_sc_hd__xnor2_1 _213_ (
    .A(_128_),
    .B(_050_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__nor2_1 _214_ (
    .A(enable_baud),
    .B(accumulator[3]),
    .Y(_052_)
  );
  sky130_fd_sc_hd__a211oi_1 _215_ (
    .A1(enable_baud),
    .A2(_051_),
    .B1(_052_),
    .C1(rst),
    .Y(_004_)
  );
  sky130_fd_sc_hd__xnor2_1 _216_ (
    .A(_119_),
    .B(_130_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__nor2_1 _217_ (
    .A(enable_baud),
    .B(accumulator[4]),
    .Y(_054_)
  );
  sky130_fd_sc_hd__a211oi_1 _218_ (
    .A1(enable_baud),
    .A2(_053_),
    .B1(_054_),
    .C1(rst),
    .Y(_005_)
  );
  sky130_fd_sc_hd__nor2_1 _219_ (
    .A(_115_),
    .B(_116_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__xor2_1 _220_ (
    .A(_131_),
    .B(_055_),
    .X(_056_)
  );
  sky130_fd_sc_hd__nor2_1 _221_ (
    .A(enable_baud),
    .B(accumulator[5]),
    .Y(_057_)
  );
  sky130_fd_sc_hd__a211oi_1 _222_ (
    .A1(enable_baud),
    .A2(_056_),
    .B1(_057_),
    .C1(rst),
    .Y(_006_)
  );
  sky130_fd_sc_hd__o21ai_0 _223_ (
    .A1(_116_),
    .A2(_132_),
    .B1(_114_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__nand2b_1 _224_ (
    .A_N(_133_),
    .B(_058_),
    .Y(_059_)
  );
  sky130_fd_sc_hd__nor2_1 _225_ (
    .A(enable_baud),
    .B(accumulator[6]),
    .Y(_060_)
  );
  sky130_fd_sc_hd__a211oi_1 _226_ (
    .A1(enable_baud),
    .A2(_059_),
    .B1(_060_),
    .C1(rst),
    .Y(_007_)
  );
  sky130_fd_sc_hd__nor2_1 _227_ (
    .A(_113_),
    .B(_133_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__xnor2_1 _228_ (
    .A(_112_),
    .B(_061_),
    .Y(_062_)
  );
  sky130_fd_sc_hd__nor2_1 _229_ (
    .A(enable_baud),
    .B(accumulator[7]),
    .Y(_063_)
  );
  sky130_fd_sc_hd__a211oi_1 _230_ (
    .A1(enable_baud),
    .A2(_062_),
    .B1(_063_),
    .C1(rst),
    .Y(_008_)
  );
  sky130_fd_sc_hd__xnor2_1 _231_ (
    .A(_135_),
    .B(_025_),
    .Y(_064_)
  );
  sky130_fd_sc_hd__nor2_1 _232_ (
    .A(enable_baud),
    .B(accumulator[8]),
    .Y(_065_)
  );
  sky130_fd_sc_hd__a211oi_1 _233_ (
    .A1(enable_baud),
    .A2(_064_),
    .B1(_065_),
    .C1(rst),
    .Y(_009_)
  );
  sky130_fd_sc_hd__nand2_1 _234_ (
    .A(_108_),
    .B(_110_),
    .Y(_066_)
  );
  sky130_fd_sc_hd__xnor2_1 _235_ (
    .A(_026_),
    .B(_066_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__nor2_1 _236_ (
    .A(enable_baud),
    .B(accumulator[9]),
    .Y(_068_)
  );
  sky130_fd_sc_hd__a211oi_1 _237_ (
    .A1(enable_baud),
    .A2(_067_),
    .B1(_068_),
    .C1(rst),
    .Y(_010_)
  );
  sky130_fd_sc_hd__xor2_1 _238_ (
    .A(_107_),
    .B(_028_),
    .X(_069_)
  );
  sky130_fd_sc_hd__nor2_1 _239_ (
    .A(enable_baud),
    .B(accumulator[10]),
    .Y(_070_)
  );
  sky130_fd_sc_hd__a211oi_1 _240_ (
    .A1(enable_baud),
    .A2(_069_),
    .B1(_070_),
    .C1(rst),
    .Y(_011_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _241_ (
    .A(_102_),
    .SLEEP(_103_),
    .X(_071_)
  );
  sky130_fd_sc_hd__xor2_1 _242_ (
    .A(_029_),
    .B(_071_),
    .X(_072_)
  );
  sky130_fd_sc_hd__nor2_1 _243_ (
    .A(enable_baud),
    .B(accumulator[11]),
    .Y(_073_)
  );
  sky130_fd_sc_hd__a211oi_1 _244_ (
    .A1(enable_baud),
    .A2(_072_),
    .B1(_073_),
    .C1(rst),
    .Y(_012_)
  );
  sky130_fd_sc_hd__xor2_1 _245_ (
    .A(_101_),
    .B(_030_),
    .X(_074_)
  );
  sky130_fd_sc_hd__nor2_1 _246_ (
    .A(enable_baud),
    .B(accumulator[12]),
    .Y(_075_)
  );
  sky130_fd_sc_hd__a211oi_1 _247_ (
    .A1(enable_baud),
    .A2(_074_),
    .B1(_075_),
    .C1(rst),
    .Y(_013_)
  );
  sky130_fd_sc_hd__a21oi_1 _248_ (
    .A1(accumulator[12]),
    .A2(_099_),
    .B1(_031_),
    .Y(_076_)
  );
  sky130_fd_sc_hd__xor2_1 _249_ (
    .A(_097_),
    .B(_076_),
    .X(_077_)
  );
  sky130_fd_sc_hd__nor2_1 _250_ (
    .A(enable_baud),
    .B(accumulator[13]),
    .Y(_078_)
  );
  sky130_fd_sc_hd__a211oi_1 _251_ (
    .A1(enable_baud),
    .A2(_077_),
    .B1(_078_),
    .C1(rst),
    .Y(_014_)
  );
  sky130_fd_sc_hd__xor2_1 _252_ (
    .A(_092_),
    .B(_034_),
    .X(_079_)
  );
  sky130_fd_sc_hd__nor2_1 _253_ (
    .A(enable_baud),
    .B(accumulator[14]),
    .Y(_080_)
  );
  sky130_fd_sc_hd__a211oi_1 _254_ (
    .A1(enable_baud),
    .A2(_079_),
    .B1(_080_),
    .C1(rst),
    .Y(_015_)
  );
  sky130_fd_sc_hd__a21oi_1 _255_ (
    .A1(enable_baud),
    .A2(_036_),
    .B1(accumulator[15]),
    .Y(_081_)
  );
  sky130_fd_sc_hd__nor3_1 _256_ (
    .A(rst),
    .B(_038_),
    .C(_081_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__nor2_1 _257_ (
    .A(accumulator[16]),
    .B(_038_),
    .Y(_082_)
  );
  sky130_fd_sc_hd__nor3_1 _258_ (
    .A(rst),
    .B(_039_),
    .C(_082_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__and2_0 _259_ (
    .A(accumulator[17]),
    .B(_039_),
    .X(_083_)
  );
  sky130_fd_sc_hd__nor2_1 _260_ (
    .A(accumulator[17]),
    .B(_039_),
    .Y(_084_)
  );
  sky130_fd_sc_hd__nor3_1 _261_ (
    .A(rst),
    .B(_083_),
    .C(_084_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__a21oi_1 _262_ (
    .A1(accumulator[18]),
    .A2(_083_),
    .B1(rst),
    .Y(_085_)
  );
  sky130_fd_sc_hd__o21a_1 _263_ (
    .A1(accumulator[18]),
    .A2(_083_),
    .B1(_085_),
    .X(_019_)
  );
  sky130_fd_sc_hd__a21oi_1 _264_ (
    .A1(accumulator[18]),
    .A2(_083_),
    .B1(accumulator[19]),
    .Y(_086_)
  );
  sky130_fd_sc_hd__a211oi_1 _265_ (
    .A1(_039_),
    .A2(_040_),
    .B1(_086_),
    .C1(rst),
    .Y(_020_)
  );
  sky130_fd_sc_hd__a21oi_1 _266_ (
    .A1(_039_),
    .A2(_040_),
    .B1(accumulator[20]),
    .Y(_087_)
  );
  sky130_fd_sc_hd__nor3_1 _267_ (
    .A(rst),
    .B(_041_),
    .C(_087_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__a21oi_1 _268_ (
    .A1(accumulator[21]),
    .A2(_041_),
    .B1(rst),
    .Y(_088_)
  );
  sky130_fd_sc_hd__o21a_1 _269_ (
    .A1(accumulator[21]),
    .A2(_041_),
    .B1(_088_),
    .X(_022_)
  );
  sky130_fd_sc_hd__a21oi_1 _270_ (
    .A1(accumulator[21]),
    .A2(_041_),
    .B1(accumulator[22]),
    .Y(_089_)
  );
  sky130_fd_sc_hd__nor3_1 _271_ (
    .A(rst),
    .B(_042_),
    .C(_089_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__a31oi_1 _272_ (
    .A1(accumulator[22]),
    .A2(accumulator[21]),
    .A3(_041_),
    .B1(accumulator[23]),
    .Y(_090_)
  );
  sky130_fd_sc_hd__nor3_1 _273_ (
    .A(rst),
    .B(_043_),
    .C(_090_),
    .Y(_024_)
  );
  (* src = "baud_rate_selector.v:28.1-50.4" *)
  sky130_fd_sc_hd__dfxtp_1 _274_ (
    .CLK(clk),
    .D(_000_),
    .Q(baud)
  );
  (* src = "baud_rate_selector.v:28.1-50.4" *)
  sky130_fd_sc_hd__dfxtp_1 _275_ (
    .CLK(clk),
    .D(_001_),
    .Q(accumulator[0])
  );
  (* src = "baud_rate_selector.v:28.1-50.4" *)
  sky130_fd_sc_hd__dfxtp_1 _276_ (
    .CLK(clk),
    .D(_002_),
    .Q(accumulator[1])
  );
  (* src = "baud_rate_selector.v:28.1-50.4" *)
  sky130_fd_sc_hd__dfxtp_1 _277_ (
    .CLK(clk),
    .D(_003_),
    .Q(accumulator[2])
  );
  (* src = "baud_rate_selector.v:28.1-50.4" *)
  sky130_fd_sc_hd__dfxtp_1 _278_ (
    .CLK(clk),
    .D(_004_),
    .Q(accumulator[3])
  );
  (* src = "baud_rate_selector.v:28.1-50.4" *)
  sky130_fd_sc_hd__dfxtp_1 _279_ (
    .CLK(clk),
    .D(_005_),
    .Q(accumulator[4])
  );
  (* src = "baud_rate_selector.v:28.1-50.4" *)
  sky130_fd_sc_hd__dfxtp_1 _280_ (
    .CLK(clk),
    .D(_006_),
    .Q(accumulator[5])
  );
  (* src = "baud_rate_selector.v:28.1-50.4" *)
  sky130_fd_sc_hd__dfxtp_1 _281_ (
    .CLK(clk),
    .D(_007_),
    .Q(accumulator[6])
  );
  (* src = "baud_rate_selector.v:28.1-50.4" *)
  sky130_fd_sc_hd__dfxtp_1 _282_ (
    .CLK(clk),
    .D(_008_),
    .Q(accumulator[7])
  );
  (* src = "baud_rate_selector.v:28.1-50.4" *)
  sky130_fd_sc_hd__dfxtp_1 _283_ (
    .CLK(clk),
    .D(_009_),
    .Q(accumulator[8])
  );
  (* src = "baud_rate_selector.v:28.1-50.4" *)
  sky130_fd_sc_hd__dfxtp_1 _284_ (
    .CLK(clk),
    .D(_010_),
    .Q(accumulator[9])
  );
  (* src = "baud_rate_selector.v:28.1-50.4" *)
  sky130_fd_sc_hd__dfxtp_1 _285_ (
    .CLK(clk),
    .D(_011_),
    .Q(accumulator[10])
  );
  (* src = "baud_rate_selector.v:28.1-50.4" *)
  sky130_fd_sc_hd__dfxtp_1 _286_ (
    .CLK(clk),
    .D(_012_),
    .Q(accumulator[11])
  );
  (* src = "baud_rate_selector.v:28.1-50.4" *)
  sky130_fd_sc_hd__dfxtp_1 _287_ (
    .CLK(clk),
    .D(_013_),
    .Q(accumulator[12])
  );
  (* src = "baud_rate_selector.v:28.1-50.4" *)
  sky130_fd_sc_hd__dfxtp_1 _288_ (
    .CLK(clk),
    .D(_014_),
    .Q(accumulator[13])
  );
  (* src = "baud_rate_selector.v:28.1-50.4" *)
  sky130_fd_sc_hd__dfxtp_1 _289_ (
    .CLK(clk),
    .D(_015_),
    .Q(accumulator[14])
  );
  (* src = "baud_rate_selector.v:28.1-50.4" *)
  sky130_fd_sc_hd__dfxtp_1 _290_ (
    .CLK(clk),
    .D(_016_),
    .Q(accumulator[15])
  );
  (* src = "baud_rate_selector.v:28.1-50.4" *)
  sky130_fd_sc_hd__dfxtp_1 _291_ (
    .CLK(clk),
    .D(_017_),
    .Q(accumulator[16])
  );
  (* src = "baud_rate_selector.v:28.1-50.4" *)
  sky130_fd_sc_hd__dfxtp_1 _292_ (
    .CLK(clk),
    .D(_018_),
    .Q(accumulator[17])
  );
  (* src = "baud_rate_selector.v:28.1-50.4" *)
  sky130_fd_sc_hd__dfxtp_1 _293_ (
    .CLK(clk),
    .D(_019_),
    .Q(accumulator[18])
  );
  (* src = "baud_rate_selector.v:28.1-50.4" *)
  sky130_fd_sc_hd__dfxtp_1 _294_ (
    .CLK(clk),
    .D(_020_),
    .Q(accumulator[19])
  );
  (* src = "baud_rate_selector.v:28.1-50.4" *)
  sky130_fd_sc_hd__dfxtp_1 _295_ (
    .CLK(clk),
    .D(_021_),
    .Q(accumulator[20])
  );
  (* src = "baud_rate_selector.v:28.1-50.4" *)
  sky130_fd_sc_hd__dfxtp_1 _296_ (
    .CLK(clk),
    .D(_022_),
    .Q(accumulator[21])
  );
  (* src = "baud_rate_selector.v:28.1-50.4" *)
  sky130_fd_sc_hd__dfxtp_1 _297_ (
    .CLK(clk),
    .D(_023_),
    .Q(accumulator[22])
  );
  (* src = "baud_rate_selector.v:28.1-50.4" *)
  sky130_fd_sc_hd__dfxtp_1 _298_ (
    .CLK(clk),
    .D(_024_),
    .Q(accumulator[23])
  );
endmodule

(* src = "reciever.v:1.1-91.10" *)
module reciever(clk, rst, rxd, baud_tick, o_data, o_data_valid);
  (* src = "reciever.v:21.5-89.8" *)
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  (* src = "reciever.v:5.16-5.25" *)
  input baud_tick;
  wire baud_tick;
  (* src = "reciever.v:2.16-2.19" *)
  input clk;
  wire clk;
  (* src = "reciever.v:6.22-6.28" *)
  output [7:0] o_data;
  wire [7:0] o_data;
  (* src = "reciever.v:7.32-7.44" *)
  output o_data_valid;
  wire o_data_valid;
  (* src = "reciever.v:18.15-18.26" *)
  wire [2:0] r_bit_count;
  (* src = "reciever.v:19.15-19.28" *)
  wire [7:0] r_data_buffer;
  (* src = "reciever.v:17.15-17.22" *)
  wire [2:0] r_state;
  (* src = "reciever.v:3.16-3.19" *)
  input rst;
  wire rst;
  (* src = "reciever.v:4.16-4.19" *)
  input rxd;
  wire rxd;
  sky130_fd_sc_hd__clkinv_1 _083_ (
    .A(r_bit_count[1]),
    .Y(_064_)
  );
  sky130_fd_sc_hd__clkinv_1 _084_ (
    .A(r_bit_count[0]),
    .Y(_065_)
  );
  sky130_fd_sc_hd__clkinv_1 _085_ (
    .A(r_data_buffer[3]),
    .Y(_066_)
  );
  sky130_fd_sc_hd__clkinv_1 _086_ (
    .A(rst),
    .Y(_001_)
  );
  sky130_fd_sc_hd__nor2_1 _087_ (
    .A(r_state[2]),
    .B(r_state[0]),
    .Y(_067_)
  );
  sky130_fd_sc_hd__nand2b_1 _088_ (
    .A_N(r_state[1]),
    .B(rxd),
    .Y(_068_)
  );
  sky130_fd_sc_hd__and3_1 _089_ (
    .A(baud_tick),
    .B(_067_),
    .C(_068_),
    .X(_069_)
  );
  sky130_fd_sc_hd__and2_0 _090_ (
    .A(r_bit_count[1]),
    .B(r_bit_count[0]),
    .X(_070_)
  );
  sky130_fd_sc_hd__a41oi_1 _091_ (
    .A1(baud_tick),
    .A2(_067_),
    .A3(_068_),
    .A4(_070_),
    .B1(r_bit_count[2]),
    .Y(_071_)
  );
  sky130_fd_sc_hd__nand3_1 _092_ (
    .A(r_bit_count[2]),
    .B(r_bit_count[1]),
    .C(r_bit_count[0]),
    .Y(_072_)
  );
  sky130_fd_sc_hd__nand3_1 _093_ (
    .A(r_state[1]),
    .B(_067_),
    .C(_072_),
    .Y(_073_)
  );
  sky130_fd_sc_hd__a21oi_1 _094_ (
    .A1(_069_),
    .A2(_073_),
    .B1(_071_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__xor2_1 _095_ (
    .A(r_bit_count[1]),
    .B(r_bit_count[0]),
    .X(_074_)
  );
  sky130_fd_sc_hd__nor4bb_1 _096_ (
    .A(r_state[2]),
    .B(r_state[0]),
    .C_N(baud_tick),
    .D_N(r_state[1]),
    .Y(_075_)
  );
  sky130_fd_sc_hd__nand4bb_1 _097_ (
    .A_N(r_state[2]),
    .B_N(r_state[0]),
    .C(baud_tick),
    .D(r_state[1]),
    .Y(_076_)
  );
  sky130_fd_sc_hd__nand2_1 _098_ (
    .A(_074_),
    .B(_075_),
    .Y(_077_)
  );
  sky130_fd_sc_hd__o21ai_0 _099_ (
    .A1(_064_),
    .A2(_069_),
    .B1(_077_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__nand2_1 _100_ (
    .A(_065_),
    .B(_075_),
    .Y(_078_)
  );
  sky130_fd_sc_hd__o21ai_0 _101_ (
    .A1(_065_),
    .A2(_069_),
    .B1(_078_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__nand2_1 _102_ (
    .A(r_state[1]),
    .B(r_state[0]),
    .Y(_079_)
  );
  sky130_fd_sc_hd__nand2_1 _103_ (
    .A(baud_tick),
    .B(rxd),
    .Y(_080_)
  );
  sky130_fd_sc_hd__nor3_1 _104_ (
    .A(r_state[2]),
    .B(_079_),
    .C(_080_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__nor3b_1 _105_ (
    .A(r_state[2]),
    .B(baud_tick),
    .C_N(r_state[1]),
    .Y(_081_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _106_ (
    .A(_069_),
    .SLEEP(_081_),
    .X(_041_)
  );
  sky130_fd_sc_hd__nand3_1 _107_ (
    .A(r_bit_count[2]),
    .B(_070_),
    .C(_075_),
    .Y(_082_)
  );
  sky130_fd_sc_hd__o31ai_1 _108_ (
    .A1(r_state[2]),
    .A2(baud_tick),
    .A3(_079_),
    .B1(_082_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__nor3b_1 _109_ (
    .A(r_state[1]),
    .B(r_state[0]),
    .C_N(r_state[2]),
    .Y(_000_)
  );
  sky130_fd_sc_hd__mux2_1 _110_ (
    .A0(o_data[7]),
    .A1(r_data_buffer[7]),
    .S(_000_),
    .X(_039_)
  );
  sky130_fd_sc_hd__mux2_1 _111_ (
    .A0(o_data[6]),
    .A1(r_data_buffer[6]),
    .S(_000_),
    .X(_038_)
  );
  sky130_fd_sc_hd__mux2_1 _112_ (
    .A0(o_data[5]),
    .A1(r_data_buffer[5]),
    .S(_000_),
    .X(_037_)
  );
  sky130_fd_sc_hd__mux2_1 _113_ (
    .A0(o_data[4]),
    .A1(r_data_buffer[4]),
    .S(_000_),
    .X(_036_)
  );
  sky130_fd_sc_hd__nor2_1 _114_ (
    .A(o_data[3]),
    .B(_000_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__a21oi_1 _115_ (
    .A1(_066_),
    .A2(_000_),
    .B1(_046_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__mux2_1 _116_ (
    .A0(o_data[2]),
    .A1(r_data_buffer[2]),
    .S(_000_),
    .X(_034_)
  );
  sky130_fd_sc_hd__mux2_1 _117_ (
    .A0(o_data[1]),
    .A1(r_data_buffer[1]),
    .S(_000_),
    .X(_033_)
  );
  sky130_fd_sc_hd__mux2_1 _118_ (
    .A0(o_data[0]),
    .A1(r_data_buffer[0]),
    .S(_000_),
    .X(_032_)
  );
  sky130_fd_sc_hd__nand2_1 _119_ (
    .A(rxd),
    .B(_070_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__o21ai_0 _120_ (
    .A1(r_bit_count[1]),
    .A2(r_bit_count[0]),
    .B1(r_bit_count[2]),
    .Y(_048_)
  );
  sky130_fd_sc_hd__nor3_1 _121_ (
    .A(r_bit_count[2]),
    .B(r_bit_count[1]),
    .C(r_bit_count[0]),
    .Y(_049_)
  );
  sky130_fd_sc_hd__or3_1 _122_ (
    .A(r_bit_count[2]),
    .B(r_bit_count[1]),
    .C(r_bit_count[0]),
    .X(_050_)
  );
  sky130_fd_sc_hd__a21o_1 _123_ (
    .A1(_048_),
    .A2(_050_),
    .B1(_076_),
    .X(_051_)
  );
  sky130_fd_sc_hd__o2bb2ai_1 _124_ (
    .A1_N(r_data_buffer[7]),
    .A2_N(_082_),
    .B1(_047_),
    .B2(_051_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__nand4_1 _125_ (
    .A(r_bit_count[2]),
    .B(r_bit_count[1]),
    .C(_065_),
    .D(_075_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__nand3_1 _126_ (
    .A(_065_),
    .B(rxd),
    .C(_050_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__nand3_1 _127_ (
    .A(r_bit_count[1]),
    .B(_065_),
    .C(rxd),
    .Y(_054_)
  );
  sky130_fd_sc_hd__o2bb2ai_1 _128_ (
    .A1_N(r_data_buffer[6]),
    .A2_N(_052_),
    .B1(_054_),
    .B2(_051_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__nand4_1 _129_ (
    .A(r_bit_count[2]),
    .B(_064_),
    .C(r_bit_count[0]),
    .D(_075_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__nand3_1 _130_ (
    .A(_064_),
    .B(r_bit_count[0]),
    .C(rxd),
    .Y(_056_)
  );
  sky130_fd_sc_hd__o2bb2ai_1 _131_ (
    .A1_N(r_data_buffer[5]),
    .A2_N(_055_),
    .B1(_056_),
    .B2(_051_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__o41ai_1 _132_ (
    .A1(r_bit_count[1]),
    .A2(r_bit_count[0]),
    .A3(_076_),
    .A4(_049_),
    .B1(r_data_buffer[4]),
    .Y(_057_)
  );
  sky130_fd_sc_hd__o31ai_1 _133_ (
    .A1(_074_),
    .A2(_076_),
    .A3(_053_),
    .B1(_057_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__nand3_1 _134_ (
    .A(_075_),
    .B(_048_),
    .C(_050_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__nor4_1 _135_ (
    .A(r_bit_count[2]),
    .B(_064_),
    .C(_065_),
    .D(_076_),
    .Y(_059_)
  );
  sky130_fd_sc_hd__o22ai_1 _136_ (
    .A1(_047_),
    .A2(_058_),
    .B1(_059_),
    .B2(_066_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__o41ai_1 _137_ (
    .A1(r_bit_count[2]),
    .A2(_064_),
    .A3(r_bit_count[0]),
    .A4(_076_),
    .B1(r_data_buffer[2]),
    .Y(_060_)
  );
  sky130_fd_sc_hd__o21ai_0 _138_ (
    .A1(_054_),
    .A2(_058_),
    .B1(_060_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__o41ai_1 _139_ (
    .A1(r_bit_count[2]),
    .A2(r_bit_count[1]),
    .A3(_065_),
    .A4(_076_),
    .B1(r_data_buffer[1]),
    .Y(_061_)
  );
  sky130_fd_sc_hd__o21ai_0 _140_ (
    .A1(_056_),
    .A2(_058_),
    .B1(_061_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__nand3_1 _141_ (
    .A(rxd),
    .B(_075_),
    .C(_049_),
    .Y(_062_)
  );
  sky130_fd_sc_hd__o21ai_0 _142_ (
    .A1(_076_),
    .A2(_050_),
    .B1(r_data_buffer[0]),
    .Y(_063_)
  );
  sky130_fd_sc_hd__nand2_1 _143_ (
    .A(_062_),
    .B(_063_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__clkinv_1 _144_ (
    .A(rst),
    .Y(_002_)
  );
  sky130_fd_sc_hd__clkinv_1 _145_ (
    .A(rst),
    .Y(_003_)
  );
  sky130_fd_sc_hd__clkinv_1 _146_ (
    .A(rst),
    .Y(_004_)
  );
  sky130_fd_sc_hd__clkinv_1 _147_ (
    .A(rst),
    .Y(_005_)
  );
  sky130_fd_sc_hd__clkinv_1 _148_ (
    .A(rst),
    .Y(_006_)
  );
  sky130_fd_sc_hd__clkinv_1 _149_ (
    .A(rst),
    .Y(_007_)
  );
  sky130_fd_sc_hd__clkinv_1 _150_ (
    .A(rst),
    .Y(_008_)
  );
  sky130_fd_sc_hd__clkinv_1 _151_ (
    .A(rst),
    .Y(_009_)
  );
  sky130_fd_sc_hd__clkinv_1 _152_ (
    .A(rst),
    .Y(_010_)
  );
  sky130_fd_sc_hd__clkinv_1 _153_ (
    .A(rst),
    .Y(_011_)
  );
  sky130_fd_sc_hd__clkinv_1 _154_ (
    .A(rst),
    .Y(_012_)
  );
  sky130_fd_sc_hd__clkinv_1 _155_ (
    .A(rst),
    .Y(_013_)
  );
  sky130_fd_sc_hd__clkinv_1 _156_ (
    .A(rst),
    .Y(_014_)
  );
  sky130_fd_sc_hd__clkinv_1 _157_ (
    .A(rst),
    .Y(_015_)
  );
  sky130_fd_sc_hd__clkinv_1 _158_ (
    .A(rst),
    .Y(_016_)
  );
  sky130_fd_sc_hd__clkinv_1 _159_ (
    .A(rst),
    .Y(_017_)
  );
  sky130_fd_sc_hd__clkinv_1 _160_ (
    .A(rst),
    .Y(_018_)
  );
  sky130_fd_sc_hd__clkinv_1 _161_ (
    .A(rst),
    .Y(_019_)
  );
  sky130_fd_sc_hd__clkinv_1 _162_ (
    .A(rst),
    .Y(_020_)
  );
  sky130_fd_sc_hd__clkinv_1 _163_ (
    .A(rst),
    .Y(_021_)
  );
  sky130_fd_sc_hd__clkinv_1 _164_ (
    .A(rst),
    .Y(_022_)
  );
  sky130_fd_sc_hd__clkinv_1 _165_ (
    .A(rst),
    .Y(_023_)
  );
  (* src = "reciever.v:21.5-89.8" *)
  sky130_fd_sc_hd__dfrtp_1 _166_ (
    .CLK(clk),
    .D(_024_),
    .Q(r_data_buffer[0]),
    .RESET_B(_001_)
  );
  (* src = "reciever.v:21.5-89.8" *)
  sky130_fd_sc_hd__dfrtp_1 _167_ (
    .CLK(clk),
    .D(_025_),
    .Q(r_data_buffer[1]),
    .RESET_B(_002_)
  );
  (* src = "reciever.v:21.5-89.8" *)
  sky130_fd_sc_hd__dfrtp_1 _168_ (
    .CLK(clk),
    .D(_026_),
    .Q(r_data_buffer[2]),
    .RESET_B(_003_)
  );
  (* src = "reciever.v:21.5-89.8" *)
  sky130_fd_sc_hd__dfrtp_1 _169_ (
    .CLK(clk),
    .D(_027_),
    .Q(r_data_buffer[3]),
    .RESET_B(_004_)
  );
  (* src = "reciever.v:21.5-89.8" *)
  sky130_fd_sc_hd__dfrtp_1 _170_ (
    .CLK(clk),
    .D(_028_),
    .Q(r_data_buffer[4]),
    .RESET_B(_005_)
  );
  (* src = "reciever.v:21.5-89.8" *)
  sky130_fd_sc_hd__dfrtp_1 _171_ (
    .CLK(clk),
    .D(_029_),
    .Q(r_data_buffer[5]),
    .RESET_B(_006_)
  );
  (* src = "reciever.v:21.5-89.8" *)
  sky130_fd_sc_hd__dfrtp_1 _172_ (
    .CLK(clk),
    .D(_030_),
    .Q(r_data_buffer[6]),
    .RESET_B(_007_)
  );
  (* src = "reciever.v:21.5-89.8" *)
  sky130_fd_sc_hd__dfrtp_1 _173_ (
    .CLK(clk),
    .D(_031_),
    .Q(r_data_buffer[7]),
    .RESET_B(_008_)
  );
  (* src = "reciever.v:21.5-89.8" *)
  sky130_fd_sc_hd__dfrtp_1 _174_ (
    .CLK(clk),
    .D(_000_),
    .Q(o_data_valid),
    .RESET_B(_009_)
  );
  (* src = "reciever.v:21.5-89.8" *)
  sky130_fd_sc_hd__dfrtp_1 _175_ (
    .CLK(clk),
    .D(_032_),
    .Q(o_data[0]),
    .RESET_B(_010_)
  );
  (* src = "reciever.v:21.5-89.8" *)
  sky130_fd_sc_hd__dfrtp_1 _176_ (
    .CLK(clk),
    .D(_033_),
    .Q(o_data[1]),
    .RESET_B(_011_)
  );
  (* src = "reciever.v:21.5-89.8" *)
  sky130_fd_sc_hd__dfrtp_1 _177_ (
    .CLK(clk),
    .D(_034_),
    .Q(o_data[2]),
    .RESET_B(_012_)
  );
  (* src = "reciever.v:21.5-89.8" *)
  sky130_fd_sc_hd__dfrtp_1 _178_ (
    .CLK(clk),
    .D(_035_),
    .Q(o_data[3]),
    .RESET_B(_013_)
  );
  (* src = "reciever.v:21.5-89.8" *)
  sky130_fd_sc_hd__dfrtp_1 _179_ (
    .CLK(clk),
    .D(_036_),
    .Q(o_data[4]),
    .RESET_B(_014_)
  );
  (* src = "reciever.v:21.5-89.8" *)
  sky130_fd_sc_hd__dfrtp_1 _180_ (
    .CLK(clk),
    .D(_037_),
    .Q(o_data[5]),
    .RESET_B(_015_)
  );
  (* src = "reciever.v:21.5-89.8" *)
  sky130_fd_sc_hd__dfrtp_1 _181_ (
    .CLK(clk),
    .D(_038_),
    .Q(o_data[6]),
    .RESET_B(_016_)
  );
  (* src = "reciever.v:21.5-89.8" *)
  sky130_fd_sc_hd__dfrtp_1 _182_ (
    .CLK(clk),
    .D(_039_),
    .Q(o_data[7]),
    .RESET_B(_017_)
  );
  (* src = "reciever.v:21.5-89.8" *)
  sky130_fd_sc_hd__dfrtp_1 _183_ (
    .CLK(clk),
    .D(_040_),
    .Q(r_state[0]),
    .RESET_B(_018_)
  );
  (* src = "reciever.v:21.5-89.8" *)
  sky130_fd_sc_hd__dfrtp_1 _184_ (
    .CLK(clk),
    .D(_041_),
    .Q(r_state[1]),
    .RESET_B(_019_)
  );
  (* src = "reciever.v:21.5-89.8" *)
  sky130_fd_sc_hd__dfrtp_1 _185_ (
    .CLK(clk),
    .D(_042_),
    .Q(r_state[2]),
    .RESET_B(_020_)
  );
  (* src = "reciever.v:21.5-89.8" *)
  sky130_fd_sc_hd__dfrtp_1 _186_ (
    .CLK(clk),
    .D(_043_),
    .Q(r_bit_count[0]),
    .RESET_B(_021_)
  );
  (* src = "reciever.v:21.5-89.8" *)
  sky130_fd_sc_hd__dfrtp_1 _187_ (
    .CLK(clk),
    .D(_044_),
    .Q(r_bit_count[1]),
    .RESET_B(_022_)
  );
  (* src = "reciever.v:21.5-89.8" *)
  sky130_fd_sc_hd__dfrtp_1 _188_ (
    .CLK(clk),
    .D(_045_),
    .Q(r_bit_count[2]),
    .RESET_B(_023_)
  );
endmodule

(* src = "transmitter.v:1.1-80.10" *)
module transmitter(clk, rst, trans_data, tran_start, baud, txd, tx_busy);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  (* src = "transmitter.v:6.21-6.25" *)
  input baud;
  wire baud;
  (* src = "transmitter.v:22.7-22.13" *)
  wire baud_d;
  (* src = "transmitter.v:2.21-2.24" *)
  input clk;
  wire clk;
  (* src = "transmitter.v:19.13-19.20" *)
  wire [2:0] counter;
  (* src = "transmitter.v:17.20-17.30" *)
  wire [1:0] next_state;
  (* src = "transmitter.v:3.21-3.24" *)
  input rst;
  wire rst;
  (* src = "transmitter.v:17.13-17.18" *)
  wire [1:0] state;
  (* src = "transmitter.v:5.21-5.31" *)
  input tran_start;
  wire tran_start;
  (* src = "transmitter.v:4.21-4.31" *)
  input [7:0] trans_data;
  wire [7:0] trans_data;
  (* src = "transmitter.v:18.13-18.22" *)
  wire [7:0] tx_buffer;
  (* src = "transmitter.v:8.21-8.28" *)
  output tx_busy;
  wire tx_busy;
  (* src = "transmitter.v:7.21-7.24" *)
  output txd;
  wire txd;
  sky130_fd_sc_hd__clkinv_1 _41_ (
    .A(state[0]),
    .Y(_25_)
  );
  sky130_fd_sc_hd__clkinv_1 _42_ (
    .A(rst),
    .Y(_00_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _43_ (
    .A(baud),
    .SLEEP(baud_d),
    .X(_26_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _44_ (
    .A(state[1]),
    .SLEEP(state[0]),
    .X(_27_)
  );
  sky130_fd_sc_hd__and3_1 _45_ (
    .A(counter[0]),
    .B(_26_),
    .C(_27_),
    .X(_28_)
  );
  sky130_fd_sc_hd__a41o_1 _46_ (
    .A1(counter[1]),
    .A2(counter[0]),
    .A3(_26_),
    .A4(_27_),
    .B1(counter[2]),
    .X(_29_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _47_ (
    .A(state[0]),
    .SLEEP(state[1]),
    .X(tx_busy)
  );
  sky130_fd_sc_hd__nor3b_1 _48_ (
    .A(state[0]),
    .B(state[1]),
    .C_N(tran_start),
    .Y(_30_)
  );
  sky130_fd_sc_hd__a41oi_1 _49_ (
    .A1(counter[1]),
    .A2(counter[0]),
    .A3(_26_),
    .A4(_27_),
    .B1(_30_),
    .Y(_31_)
  );
  sky130_fd_sc_hd__nor2_1 _50_ (
    .A(counter[2]),
    .B(_30_),
    .Y(_32_)
  );
  sky130_fd_sc_hd__o21a_1 _51_ (
    .A1(_31_),
    .A2(_32_),
    .B1(_29_),
    .X(_24_)
  );
  sky130_fd_sc_hd__o21a_1 _52_ (
    .A1(counter[1]),
    .A2(_28_),
    .B1(_31_),
    .X(_23_)
  );
  sky130_fd_sc_hd__a21oi_1 _53_ (
    .A1(_26_),
    .A2(_27_),
    .B1(counter[0]),
    .Y(_33_)
  );
  sky130_fd_sc_hd__nor3_1 _54_ (
    .A(_28_),
    .B(_30_),
    .C(_33_),
    .Y(_22_)
  );
  sky130_fd_sc_hd__mux2_1 _55_ (
    .A0(tx_buffer[7]),
    .A1(trans_data[7]),
    .S(_30_),
    .X(_21_)
  );
  sky130_fd_sc_hd__mux2_1 _56_ (
    .A0(tx_buffer[6]),
    .A1(trans_data[6]),
    .S(_30_),
    .X(_20_)
  );
  sky130_fd_sc_hd__mux2_1 _57_ (
    .A0(tx_buffer[5]),
    .A1(trans_data[5]),
    .S(_30_),
    .X(_19_)
  );
  sky130_fd_sc_hd__mux2_1 _58_ (
    .A0(tx_buffer[4]),
    .A1(trans_data[4]),
    .S(_30_),
    .X(_18_)
  );
  sky130_fd_sc_hd__mux2_1 _59_ (
    .A0(tx_buffer[3]),
    .A1(trans_data[3]),
    .S(_30_),
    .X(_17_)
  );
  sky130_fd_sc_hd__mux2_1 _60_ (
    .A0(tx_buffer[2]),
    .A1(trans_data[2]),
    .S(_30_),
    .X(_16_)
  );
  sky130_fd_sc_hd__mux2_1 _61_ (
    .A0(tx_buffer[1]),
    .A1(trans_data[1]),
    .S(_30_),
    .X(_15_)
  );
  sky130_fd_sc_hd__mux2_1 _62_ (
    .A0(tx_buffer[0]),
    .A1(trans_data[0]),
    .S(_30_),
    .X(_14_)
  );
  sky130_fd_sc_hd__o22ai_1 _63_ (
    .A1(_25_),
    .A2(_26_),
    .B1(_31_),
    .B2(_32_),
    .Y(next_state[0])
  );
  sky130_fd_sc_hd__nor2_1 _64_ (
    .A(state[1]),
    .B(_26_),
    .Y(_34_)
  );
  sky130_fd_sc_hd__nand2_1 _65_ (
    .A(state[0]),
    .B(state[1]),
    .Y(_35_)
  );
  sky130_fd_sc_hd__nand2_1 _66_ (
    .A(tx_busy),
    .B(_35_),
    .Y(_36_)
  );
  sky130_fd_sc_hd__a21oi_1 _67_ (
    .A1(_26_),
    .A2(_36_),
    .B1(_34_),
    .Y(next_state[1])
  );
  sky130_fd_sc_hd__mux4_2 _68_ (
    .A0(tx_buffer[0]),
    .A1(tx_buffer[2]),
    .A2(tx_buffer[4]),
    .A3(tx_buffer[6]),
    .S0(counter[1]),
    .S1(counter[2]),
    .X(_37_)
  );
  sky130_fd_sc_hd__mux4_2 _69_ (
    .A0(tx_buffer[1]),
    .A1(tx_buffer[3]),
    .A2(tx_buffer[5]),
    .A3(tx_buffer[7]),
    .S0(counter[1]),
    .S1(counter[2]),
    .X(_38_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _70_ (
    .A(counter[0]),
    .SLEEP(_38_),
    .X(_39_)
  );
  sky130_fd_sc_hd__o21ai_0 _71_ (
    .A1(counter[0]),
    .A2(_37_),
    .B1(_27_),
    .Y(_40_)
  );
  sky130_fd_sc_hd__o21bai_1 _72_ (
    .A1(_39_),
    .A2(_40_),
    .B1_N(_36_),
    .Y(txd)
  );
  sky130_fd_sc_hd__clkinv_1 _73_ (
    .A(rst),
    .Y(_01_)
  );
  sky130_fd_sc_hd__clkinv_1 _74_ (
    .A(rst),
    .Y(_02_)
  );
  sky130_fd_sc_hd__clkinv_1 _75_ (
    .A(rst),
    .Y(_03_)
  );
  sky130_fd_sc_hd__clkinv_1 _76_ (
    .A(rst),
    .Y(_04_)
  );
  sky130_fd_sc_hd__clkinv_1 _77_ (
    .A(rst),
    .Y(_05_)
  );
  sky130_fd_sc_hd__clkinv_1 _78_ (
    .A(rst),
    .Y(_06_)
  );
  sky130_fd_sc_hd__clkinv_1 _79_ (
    .A(rst),
    .Y(_07_)
  );
  sky130_fd_sc_hd__clkinv_1 _80_ (
    .A(rst),
    .Y(_08_)
  );
  sky130_fd_sc_hd__clkinv_1 _81_ (
    .A(rst),
    .Y(_09_)
  );
  sky130_fd_sc_hd__clkinv_1 _82_ (
    .A(rst),
    .Y(_10_)
  );
  sky130_fd_sc_hd__clkinv_1 _83_ (
    .A(rst),
    .Y(_11_)
  );
  sky130_fd_sc_hd__clkinv_1 _84_ (
    .A(rst),
    .Y(_12_)
  );
  sky130_fd_sc_hd__clkinv_1 _85_ (
    .A(rst),
    .Y(_13_)
  );
  (* src = "transmitter.v:30.3-48.6" *)
  sky130_fd_sc_hd__dfrtp_1 _86_ (
    .CLK(clk),
    .D(next_state[0]),
    .Q(state[0]),
    .RESET_B(_00_)
  );
  (* src = "transmitter.v:30.3-48.6" *)
  sky130_fd_sc_hd__dfrtp_1 _87_ (
    .CLK(clk),
    .D(next_state[1]),
    .Q(state[1]),
    .RESET_B(_01_)
  );
  (* src = "transmitter.v:30.3-48.6" *)
  sky130_fd_sc_hd__dfrtp_1 _88_ (
    .CLK(clk),
    .D(_14_),
    .Q(tx_buffer[0]),
    .RESET_B(_02_)
  );
  (* src = "transmitter.v:30.3-48.6" *)
  sky130_fd_sc_hd__dfrtp_1 _89_ (
    .CLK(clk),
    .D(_15_),
    .Q(tx_buffer[1]),
    .RESET_B(_03_)
  );
  (* src = "transmitter.v:30.3-48.6" *)
  sky130_fd_sc_hd__dfrtp_1 _90_ (
    .CLK(clk),
    .D(_16_),
    .Q(tx_buffer[2]),
    .RESET_B(_04_)
  );
  (* src = "transmitter.v:30.3-48.6" *)
  sky130_fd_sc_hd__dfrtp_1 _91_ (
    .CLK(clk),
    .D(_17_),
    .Q(tx_buffer[3]),
    .RESET_B(_05_)
  );
  (* src = "transmitter.v:30.3-48.6" *)
  sky130_fd_sc_hd__dfrtp_1 _92_ (
    .CLK(clk),
    .D(_18_),
    .Q(tx_buffer[4]),
    .RESET_B(_06_)
  );
  (* src = "transmitter.v:30.3-48.6" *)
  sky130_fd_sc_hd__dfrtp_1 _93_ (
    .CLK(clk),
    .D(_19_),
    .Q(tx_buffer[5]),
    .RESET_B(_07_)
  );
  (* src = "transmitter.v:30.3-48.6" *)
  sky130_fd_sc_hd__dfrtp_1 _94_ (
    .CLK(clk),
    .D(_20_),
    .Q(tx_buffer[6]),
    .RESET_B(_08_)
  );
  (* src = "transmitter.v:30.3-48.6" *)
  sky130_fd_sc_hd__dfrtp_1 _95_ (
    .CLK(clk),
    .D(_21_),
    .Q(tx_buffer[7]),
    .RESET_B(_09_)
  );
  (* src = "transmitter.v:23.3-26.6" *)
  sky130_fd_sc_hd__dfrtp_1 _96_ (
    .CLK(clk),
    .D(baud),
    .Q(baud_d),
    .RESET_B(_10_)
  );
  (* src = "transmitter.v:30.3-48.6" *)
  sky130_fd_sc_hd__dfrtp_1 _97_ (
    .CLK(clk),
    .D(_22_),
    .Q(counter[0]),
    .RESET_B(_11_)
  );
  (* src = "transmitter.v:30.3-48.6" *)
  sky130_fd_sc_hd__dfrtp_1 _98_ (
    .CLK(clk),
    .D(_23_),
    .Q(counter[1]),
    .RESET_B(_12_)
  );
  (* src = "transmitter.v:30.3-48.6" *)
  sky130_fd_sc_hd__dfrtp_1 _99_ (
    .CLK(clk),
    .D(_24_),
    .Q(counter[2]),
    .RESET_B(_13_)
  );
endmodule

(* top =  1  *)
(* src = "UART.v:1.1-41.10" *)
module uart(clk, rst, baud_sel, tran_start, enable_baud, trans_data, rxd, txd, tx_busy, o_data, o_data_valid);
  (* src = "UART.v:16.6-16.10" *)
  wire baud;
  (* src = "UART.v:4.12-4.20" *)
  input [1:0] baud_sel;
  wire [1:0] baud_sel;
  (* src = "UART.v:2.7-2.10" *)
  input clk;
  wire clk;
  (* src = "UART.v:6.7-6.18" *)
  input enable_baud;
  wire enable_baud;
  (* src = "UART.v:11.13-11.19" *)
  output [7:0] o_data;
  wire [7:0] o_data;
  (* src = "UART.v:12.8-12.20" *)
  output o_data_valid;
  wire o_data_valid;
  (* src = "UART.v:3.7-3.10" *)
  input rst;
  wire rst;
  (* src = "UART.v:8.7-8.10" *)
  input rxd;
  wire rxd;
  (* src = "UART.v:5.7-5.17" *)
  input tran_start;
  wire tran_start;
  (* src = "UART.v:7.13-7.23" *)
  input [7:0] trans_data;
  wire [7:0] trans_data;
  (* src = "UART.v:10.8-10.15" *)
  output tx_busy;
  wire tx_busy;
  (* src = "UART.v:9.8-9.11" *)
  output txd;
  wire txd;
  (* module_not_derived = 32'd1 *)
  (* src = "UART.v:17.14-22.13" *)
  baud_sel_gen baud_generator (
    .baud(baud),
    .baud_sel(baud_sel),
    .clk(clk),
    .enable_baud(enable_baud),
    .rst(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "UART.v:33.10-39.29" *)
  reciever rec1 (
    .baud_tick(baud),
    .clk(clk),
    .o_data(o_data),
    .o_data_valid(o_data_valid),
    .rst(rst),
    .rxd(rxd)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "UART.v:24.13-31.19" *)
  transmitter tran1 (
    .baud(baud),
    .clk(clk),
    .rst(rst),
    .tran_start(tran_start),
    .trans_data(trans_data),
    .tx_busy(tx_busy),
    .txd(txd)
  );
endmodule
